#!/bin/bash

echo doing git dotty...
echo
cd ~/proj/git/dotty
git pull
echo

echo doing idea dotty...
echo
cd ~/IdeaProjects/dotty
git pull
echo

echo =====================================================================================================

echo doing git scala-cli...
echo
cd ~/proj/scala-cli/scala-cli
git pull
echo

echo doing doctor scala-cli...
echo
cd ~/proj/scala-cli/doctor
git pull
echo

echo doing idea scala-cli...
echo
cd ~/IdeaProjects/scala-cli
git pull
echo

echo doing idea doctor...
echo
cd ~/IdeaProjects/doctor
git pull
