#!/bin/bash

for dir in ~/proj/git/*; do
    echo ====================================================
    echo doing $dir...
    echo ====================================================
    (cd $dir; git pull)
    echo ----------------------------------------------------
    echo
done 2>&1 | tee /tmp/ugt.log

